AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Role:
    Type: String
    Description: The IAM Role for Lambda execution
  SharedLayerArn:
    Type: String
    Description: The ARN of the shared layer
  DemoApiId:
    Type: String
    Description: The ID of the GraphQL API

Resources:
  Endpoint1DataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !Ref DemoApiId
      Name: Endpoint1DataSource
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn: !GetAtt Endpoint1Function.Arn
      ServiceRoleArn: !Ref Role

  LambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:invokeFunction"
      FunctionName: !GetAtt Endpoint1Function.Arn
      Principal: "appsync.amazonaws.com"

  Endpoint1Resolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !Ref DemoApiId
      TypeName: "Query"
      FieldName: "endpoint1"
      DataSourceName: !GetAtt Endpoint1DataSource.Name
      Code: |
        import { util } from '@aws-appsync/utils';

        export function request(ctx) {
          const {source, args} = ctx;
          if (!args.data) {
            util.error(`Missing required field data`, 'BadRequestException');
          }
          return {
            operation: 'Invoke',
            payload: { data: args.data },
          };
        }

        export function response(ctx) {
          const { error, result } = ctx;
          if (error) {
            util.appendError(error.message, error.type, result);
          }
          return result;
        }
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0

  Endpoint1Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: endpoint1/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - !Ref SharedLayerArn
