AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DataSourceRole:
    Type: String
    Description: The IAM Role for Lambda execution
  SharedLayerArn:
    Type: String
    Description: The ARN of the shared layer
  MergedApiArn:
    Type: String
    Description: The ARN of the merged GraphQL API

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    Handler: app.lambda_handler

Resources:
  SourceApi1ApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt SourceApi1.ApiId
      Description: "API Key for the Demo API"

  SourceApi1Schema:
    Type: "AWS::AppSync::GraphQLSchema"
    Properties:
      ApiId: !GetAtt SourceApi1.ApiId
      DefinitionS3Location: ./sourceApi1.graphql

  Endpoint1Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../endpoint1/
      Layers:
        - !Ref SharedLayerArn
      Policies:
        - S3ReadPolicy:
            BucketName: frixaco-vbrato-secrets
            paths:
              - "/*"

  Endpoint1DataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt SourceApi1.ApiId
      Name: Endpoint1DataSource
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn: !GetAtt Endpoint1Function.Arn
      ServiceRoleArn: !Ref DataSourceRole

  Lambda1InvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:invokeFunction"
      FunctionName: !GetAtt Endpoint1Function.Arn
      Principal: "appsync.amazonaws.com"

  Endpoint1Resolver:
    Type: AWS::AppSync::Resolver
    Properties:
      # ApiId: !Ref SourceApi1ApiId
      ApiId: !GetAtt SourceApi1.ApiId
      TypeName: "Query"
      FieldName: "endpoint1"
      DataSourceName: !GetAtt Endpoint1DataSource.Name
      Code: |
        import { util } from '@aws-appsync/utils';

        export function request(ctx) {
          const {source, args} = ctx;
          return {
            operation: 'Invoke',
        payload: { ...args, context: ctx.identity },
          };
        }

        export function response(ctx) {
          const { error, result } = ctx;
          if (error) {
            util.appendError(error.message, error.type, result);
          }
          return result;
        }
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0

  SourceApi1:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: demo-source-api-1
      ApiType: GRAPHQL
      AuthenticationType: API_KEY
      AdditionalAuthenticationProviders:
        - AuthenticationType: AMAZON_COGNITO_USER_POOLS
          UserPoolConfig:
            UserPoolId: us-east-1_fsGHzHDM7
            AwsRegion: us-east-1

  SourceApi1Association:
    Type: AWS::AppSync::SourceApiAssociation
    DependsOn:
      - SourceApi1Schema
    Properties:
      MergedApiIdentifier: !Ref MergedApiArn
      SourceApiIdentifier: !GetAtt SourceApi1.Arn
      SourceApiAssociationConfig:
        MergeType: "AUTO_MERGE"

Outputs:
  SourceApi1Arn:
    Value: !GetAtt SourceApi1.Arn
    Export:
      Name: "SourceApi1ArnExported"
