AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  LambdaExecutionRole:
    Type: String
    Description: The IAM Role for Lambda execution
  SharedLayerArn:
    Type: String
    Description: The ARN of the shared layer
  # SourceApi1ApiId:
  #   Type: String
  #   Description: The ID of the GraphQL API
  # SourceApi1Arn:
  #   Type: String
  #   Description: The ARN of the source GraphQL API
  MergedApiArn:
    Type: String
    Description: The ARN of the merged GraphQL API

Resources:
  SourceApi1ApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      # ApiId: !Ref SourceApi1ApiId
      ApiId: !GetAtt SourceApi1.ApiId
      Description: "API Key for the Demo API"

  SourceApi1Schema:
    Type: "AWS::AppSync::GraphQLSchema"
    Properties:
      # ApiId: !Ref SourceApi1ApiId
      ApiId: !GetAtt SourceApi1.ApiId
      DefinitionS3Location: ./sourceApi1.graphql

  Endpoint1Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../endpoint1/
      Handler: app.lambda_handler
      Runtime: python3.11
      Layers:
        - !Ref SharedLayerArn

  Endpoint1DataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      # ApiId: !Ref SourceApi1ApiId
      ApiId: !GetAtt SourceApi1.ApiId
      Name: Endpoint1DataSource
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn: !GetAtt Endpoint1Function.Arn
      ServiceRoleArn: !Ref LambdaExecutionRole

  Lambda1InvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:invokeFunction"
      FunctionName: !GetAtt Endpoint1Function.Arn
      Principal: "appsync.amazonaws.com"

  Endpoint1Resolver:
    Type: AWS::AppSync::Resolver
    Properties:
      # ApiId: !Ref SourceApi1ApiId
      ApiId: !GetAtt SourceApi1.ApiId
      TypeName: "Query"
      FieldName: "endpoint1"
      DataSourceName: !GetAtt Endpoint1DataSource.Name
      Code: |
        import { util } from '@aws-appsync/utils';

        export function request(ctx) {
          const {source, args} = ctx;
          if (!args.data) {
            util.error(`Missing required field data`, 'BadRequestException');
          }
          return {
            operation: 'Invoke',
            payload: { data: args.data },
          };
        }

        export function response(ctx) {
          const { error, result } = ctx;
          if (error) {
            util.appendError(error.message, error.type, result);
          }
          return result;
        }
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0

  SourceApi1:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: demo-source-api-1
      ApiType: GRAPHQL
      AuthenticationType: API_KEY

  SourceApi1Association:
    Type: AWS::AppSync::SourceApiAssociation
    DependsOn:
      - SourceApi1Schema
    Properties:
      MergedApiIdentifier: !Ref MergedApiArn
      # SourceApiIdentifier: !Ref SourceApi1Arn
      # SourceApiIdentifier: !ImportValue SourceApi1Arn
      # SourceApiIdentifier: !Ref SourceApi1ArnExported
      # MergedApiIdentifier: !GetAtt MergedApi.Arn
      SourceApiIdentifier: !GetAtt SourceApi1.Arn
      SourceApiAssociationConfig:
        MergeType: "AUTO_MERGE"

Outputs:
  SourceApi1Arn:
    Value: !GetAtt SourceApi1.Arn
    Export:
      Name: "SourceApi1ArnExported"
