AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FfmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ffmpeg-layer
      Description: Layer with ffmpeg and ffprobe binaries
      ContentUri: s3://frixaco-lambda-layers/ffmpeg_mediainfo_layer.zip
      CompatibleRuntimes:
      - python3.11
    Metadata:
      SamResourceId: FfmpegLayer
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      Description: Layer with dependencies and utilies
      ContentUri: s3://aws-sam-cli-managed-default-samclisourcebucket-8klpbcx2xhis/77ac57793086373eb3b166ccbc348001
      CompatibleRuntimes:
      - python3.11
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.11
      SamResourceId: SharedLayer
  NotificationsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: test-realtime-notifications
    Metadata:
      SamResourceId: NotificationsTopic
  DataSourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - appsync.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: InvokeLambdaFunction
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:invokeFunction
            Resource: '*'
    Metadata:
      SamResourceId: DataSourceRole
  MergedApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - appsync.amazonaws.com
          Action:
          - sts:AssumeRole
    Metadata:
      SamResourceId: MergedApiRole
  MergedApiRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MergedApiRolePolicy
      Roles:
      - Ref: MergedApiRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - appsync:*
          Resource: '*'
    Metadata:
      SamResourceId: MergedApiRolePolicy
  SourceApi1Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-8klpbcx2xhis/93ebde176038b3046b34ff04d94246e5.template
      Parameters:
        DataSourceRole:
          Fn::GetAtt:
          - DataSourceRole
          - Arn
        SharedLayerArn:
          Ref: SharedLayer
        MergedApiArn:
          Fn::GetAtt:
          - MergedApi
          - Arn
    Metadata:
      SamResourceId: SourceApi1Stack
  SourceApi2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-8klpbcx2xhis/34ccfdb0bce80af19fe7f287eb920af8.template
      Parameters:
        DataSourceRole:
          Fn::GetAtt:
          - DataSourceRole
          - Arn
        SharedLayerArn:
          Ref: SharedLayer
        FfmpegLayerArn:
          Ref: FfmpegLayer
        MergedApiArn:
          Fn::GetAtt:
          - MergedApi
          - Arn
        NotificationsTopicArn:
          Ref: NotificationsTopic
    Metadata:
      SamResourceId: SourceApi2Stack
  MergedApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: demo-merged-api-1
      ApiType: MERGED
      AuthenticationType: API_KEY
      MergedApiExecutionRoleArn:
        Fn::GetAtt:
        - MergedApiRole
        - Arn
    Metadata:
      SamResourceId: MergedApi
  MergedApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId:
        Fn::GetAtt:
        - MergedApi
        - ApiId
      Description: API Key for the Demo API
    Metadata:
      SamResourceId: MergedApiKey
  SNSNotificationsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-8klpbcx2xhis/fada2b67226de556b9673b752eaec0a3.template
      Parameters:
        DataSourceRole:
          Fn::GetAtt:
          - DataSourceRole
          - Arn
        SharedLayerArn:
          Ref: SharedLayer
        MergedApiUrl:
          Fn::GetAtt:
          - MergedApi
          - GraphQLUrl
        MergedApiKey:
          Fn::GetAtt:
          - MergedApiKey
          - ApiKey
        NotificationsTopicArn:
          Ref: NotificationsTopic
    Metadata:
      SamResourceId: SNSNotificationsStack
Outputs:
  MergedApiUrl:
    Description: AppSync Merged API
    Value:
      Fn::GetAtt:
      - MergedApi
      - GraphQLUrl
  MergedApiKey:
    Description: API Key for authentication
    Value:
      Fn::GetAtt:
      - MergedApiKey
      - ApiKey
  NotificationsTopicArn:
    Description: ARN of the exported notifications SNS topic
    Value:
      Ref: NotificationsTopic
    Export:
      Name: NotificationsTopicArn
