AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  FfmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ffmpeg-layer
      Description: Layer with ffmpeg and ffprobe binaries
      ContentUri: "s3://frixaco-lambda-layers/ffmpeg-layer.zip"
      CompatibleRuntimes:
        - python3.11

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      Description: Layer with dependencies and utilies
      ContentUri: ../shared/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.11

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "InvokeLambdaFunction"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:invokeFunction"
                Resource: "*"

  MergedApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  MergedApiRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MergedApiRolePolicy
      Roles:
        - !Ref MergedApiRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "appsync:*"
            Resource: "*"

  SourceApi1Stack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ./child1.yaml
      Parameters:
        LambdaExecutionRole: !GetAtt LambdaExecutionRole.Arn
        SharedLayerArn: !Ref SharedLayer
        # SourceApi1ApiId: !GetAtt SourceApi1.ApiId
        MergedApiArn: !GetAtt MergedApi.Arn
        # SourceApi1Arn: !GetAtt SourceApi1.Arn

  SourceApi2Stack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ./child2.yaml
      Parameters:
        LambdaExecutionRole: !GetAtt LambdaExecutionRole.Arn
        SharedLayerArn: !Ref SharedLayer
        FfmpegLayerArn: !Ref FfmpegLayer
        # SourceApi1ApiId: !GetAtt SourceApi1.ApiId
        MergedApiArn: !GetAtt MergedApi.Arn
        # SourceApi1Arn: !GetAtt SourceApi1.Arn

  MergedApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: demo-merged-api-1
      ApiType: MERGED
      AuthenticationType: API_KEY
      MergedApiExecutionRoleArn: !GetAtt MergedApiRole.Arn

  MergedApi1ApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt MergedApi.ApiId
      Description: "API Key for the Demo API"

Outputs:
  MergedApi:
    Description: AppSync Merged API
    Value: !GetAtt MergedApi.GraphQLUrl
  MergedApi1ApiKey:
    Description: API Key for authentication
    Value: !GetAtt MergedApi1ApiKey.ApiKey
